apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider
  namespace: crossplane-system
  annotations:
    description: "ProviderConfig for managing Helm releases"
spec:
  credentials:
    source: InjectedIdentity
