apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: localstack
  namespace: localstack
spec:
  forProvider:
    chart:
      name: localstack
      version: "0.6.20"
      repository: https://localstack.github.io/helm-charts
    namespace: localstack
    skipCreateNamespace: false
    values:
      service:
        type: ClusterIP
      serviceAccount:
        create: true
  providerConfigRef:
    name: helm-provider